version: '3.8'
services:
  webhook-server:
    build: .
    ports:
      - "3000:3000"
      
    environment:
      - PORT=3000
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - DB_URI=${DB_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - USERS_COLLECTION=${USERS_COLLECTION}
      - PREFERENCES_COLLECTION=${PREFERENCES_COLLECTION}
      - APARTMENTS_COLLECTION=${APARTMENTS_COLLECTION}
      - STRIPE_SECRET_KEY_TEST=${STRIPE_SECRET_KEY_TEST}
      - STRIPE_MONTHLY_PRICE_ID=${STRIPE_MONTHLY_PRICE_ID}
      - STRIPE_YEARLY_PRICE_ID=${STRIPE_YEARLY_PRICE_ID}
      - STRIPE_YEARLY_PRICE_ID_TEST=${STRIPE_YEARLY_PRICE_ID_TEST}
      - STRIPE_PAYMENT_LINK_PROD=${STRIPE_PAYMENT_LINK_PROD}
      - STRIPE_PAYMENT_LINK_TEST=${STRIPE_PAYMENT_LINK_TEST}
      - STRIPE_BILLING_PORTAL_PROD=${STRIPE_BILLING_PORTAL_PROD}
    volumes:
      - .:/app
      - /app/node_modules