version: '3.8'
services:
  webhook-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - STRIPE_SECRET_KEY_TEST=${STRIPE_SECRET_KEY_TEST}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - .:/app
      - /app/node_modules